language: php

php:
  - 5.3
  - 5.4

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install -n
  - php app/console --env=test doctrine:database:create
  - php app/console --env=test doctrine:schema:create

script: phpunit --coverage-text -c app
