hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth/redirect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /oauth/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth/login

github_login:
    pattern: /login/check-github

logout:
   pattern:   /logout

ob_pairfony:
    resource: "@ObPairfonyBundle/Controller/"
    type:     annotation
    prefix:   /

